# Generated by Django 4.2.3 on 2023-07-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0002_author_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinPlay',
        ),
    ]
