# Generated by Django 4.2.3 on 2023-07-29 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0003_delete_coinplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('alternation_date', models.DateField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app001.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app001.author')),
            ],
        ),
    ]
